AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Resources:
  Function1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/lambda_function_1/
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref LambdaCommonCode

  Function2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/lambda_function_2/
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref LambdaCommonCode

  Function3:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/lambda_function_3/
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref LambdaCommonCode

  LambdaCommonCode:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: python3.8
    Properties:
      LayerName: lambda_common_code
      ContentUri: layers/
      CompatibleRuntimes:
        - python3.8